# src/main/resources/application-production.yml

spring:
  application:
    name: digital-wallet-prod
  config:
    activate:
      on-profile: production # Activates this config block when profile is 'production'

# --- Environment Configuration (Production) ---
server:
  port: 8081 # Use a different port for production

app:
  environment: production
  message: 'WARNING: You are running the PRODUCTION instance of the Digital Wallet API!'